01.07.2024 11:39:05 ERROR exception Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
01.07.2024 12:09:05 ERROR exception Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
01.07.2024 12:24:05 ERROR exception Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
21.07.2024 12:38:44 ERROR exception Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'resources.jetbrains.com:443'. You may need to add 'resources.jetbrains.com' to ALLOWED_HOSTS.
21.07.2024 12:39:11 ERROR exception Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'schemastore.org'. You may need to add 'schemastore.org' to ALLOWED_HOSTS.
21.07.2024 12:39:12 ERROR exception Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
21.07.2024 12:39:12 ERROR exception Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
21.07.2024 12:39:13 ERROR exception Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
21.07.2024 12:39:13 ERROR exception Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\utils\deprecation.py", line 133, in __call__
    response = self.process_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\middleware\common.py", line 48, in process_request
    host = request.get_host()
           ^^^^^^^^^^^^^^^^^^
  File "D:\pythen\pythonProject6\venv\Lib\site-packages\django\http\request.py", line 151, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: 'plugins.jetbrains.com'. You may need to add 'plugins.jetbrains.com' to ALLOWED_HOSTS.
